---
benchmarks:
#    - alarm
#    - barley
    - child
#    - insurance
#    - mildew
#    - water
#    - hailfinder
#    - hepar2
#    - win95pts
#    - andes
#    - munin1
#    - pathfinder
#    - pigs
#    - diabete